name: Build Container Image for llminference

on:
  push:
    paths:
      - "ai.core.reply/**"
      - ".github/workflows/llminference.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ghcr.io/NetBUG/llminference
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.4.0
        with:
          platforms: "amd64"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.9.0
        with:
          endpoint: builders
          config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        if: github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6.13.0
        if: github.ref == 'refs/heads/master'
        with:
          context: ./ai.core.reply
          file: ./ai.core.reply/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Build
        uses: docker/build-push-action@v6.13.0
        if: github.ref == !'refs/heads/master'
        with:
          context: .
          path: ./ai.core.reply
          file: ./ai.core.reply/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
